### ISSUE TITLE
Nested derivatives - strange order

### ISSUE THREAD

**Issue by gvdeynde** [sjelatex/derivative#14]
I'm seeing something strange with this code 

```
\documentclass{article}

\usepackage{derivative}

\begin{document}

      \[
        {\nabla}^{2}\phi(r) = \frac{1}{r^{2}}
        \odv*{\left({r}^{2}\odv*{\phi(r)}{r}\right)}{r}
      \]

\end{document}
```

Why does the code generate a "11" (is it eleven or one-one?) as the order of the derivative? 

Using LuaLaTeX 1.17.0 and derivative 1.3

What am I doing wrong?

**Comment by sjelatex** [comment]
This may be a bug in the package. I will look into it now.

**Comment by sjelatex** [comment]
It was a bug in the package. I will be update the package to CTAN, and may take a few days before it is available for download. I will also upload it here right after if you need it now.
